# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eaf6816049270771db2530b7a4a4f89a"
name = "demo"
handle = "demo-1018"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-ac55357b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
